name: versace
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.2
  
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  hive_ce_flutter: ^2.0.0
  http: ^1.4.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  hive_ce_generator: ^1.9.1
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logo-white.png
    - lib/assets/images/logo-black.png

  fonts:
    - family: Balapan
      fonts:
        - asset: lib/assets/fonts/Balapan-Regular.otf
    - family: Nonesuch
      fonts:
        - asset: lib/assets/fonts/Nonesuch-Regular.otf
    - family: OPTIRadiant
      fonts:
        - asset: lib/assets/fonts/OPTIRadiant-Bold.otf

