name: versace
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.2
  
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed: ^3.0.6
  get_it: ^8.0.3
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Balapan
      fonts:
        - asset: lib/assets/fonts/Balapan-Regular.otf
    - family: Nonesuch
      fonts:
        - asset: lib/assets/fonts/Nonesuch-Regular.otf
    - family: OPTIRadiant
      fonts:
        - asset: lib/assets/fonts/OPTIRadiant-Bold.otf

